format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $package\
    $haskell\
    $julia\
    $python\
    $conda\
    $cmd_duration\
    $jobs\
    $status\
    $character\
"""

add_newline = false

[status]
disabled = false
symbol = "💣"
